[package]
name = "uring"
version = "0.1.0"
authors = ["Tremor Team"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.8"
actix-web = "1"
actix-web-actors = "1"
awc = "0.2"
actix-codec = "0.1"

raft = "0.6.0-alpha"
rocksdb = "0.12"
slog = "2"
slog-term = "*"
slog-async = "*"

crossbeam = "0.7"
crossbeam-channel = "0.3"

byteorder = "1.3"
bytes = "0.4"
clap = "2"
env_logger = "0.7"
futures = "0.1"
rand = "0.7"
regex = "1"
serde = "1.0"
serde_json = "1.0"
tokio-io = "0.1"
protobuf = "2"

[patch.crates-io]
raft = { git = 'https://github.com/tikv/raft-rs' }

