[package]
name = "mring-node"
version = "0.1.0"
authors = ["Heinz Gies <hgies@wayfair.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

ws-proto = {path="../ws-proto"}
uring-common = {path="../uring-common"}
