name: Rust - Latest

on: [push]

jobs:
  license:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Check license headers
        run: ./checks/copyright.sh
  sanity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Safety cheks
        run: ./checks/safety.sh -a
  unused-deps:
    runs-on: ubuntu-latest
    steps:
      - name: Install deps
        run: sudo snap install remarshal rg
      - uses: actions/checkout@v1
      - name: Check for unused dependencies
        run: ./checks/deps.sh .
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Check Formating
        run: cargo fmt --all -- --check
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install deps
        run: sudo apt-get install -y libssl1.0-dev libssl1.0
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Build
        run: cargo build --all --verbose
      - name: Run tests
        run: cargo test --all --verbose
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install deps
        run: sudo apt-get install -y libssl1.0-dev libssl1.0
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Install clippy
        run: rustup component add clippy
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all
  code-coverage:
    name: Check Code Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install deps
        run: sudo apt-get install -y libssl1.0-dev libssl1.0
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - uses: wayfair-incubator/cache@v900
        id: cache-build
        with:
          path: ~/.cache/sccache
          key: sccache-cache-tarpaulin-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            sccache-cache-${{ runner.os }}-
      - uses: wayfair-incubator/cache@v900
        id: cache-sccache
        with:
          path: ~/sccache
          key: sccache-${{ runner.os }}
      - name: restore sccache
        if: steps.cache-sccache.outputs.cache-hit == 'true'
        run: cp ~/sccache/* ~/.cargo/bin
      - name: install sccache
        if: steps.cache-sccache.outputs.cache-hit != 'true'
        run: cargo install sccache
      - name: Prepare sccache command bin for cache
        if: steps.cache-sccache.outputs.cache-hit != 'true'
        run: mkdir ~/sccache; cp ~/.cargo/bin/sccache ~/sccache
      - name: install tarpaulin
        run: bash <(curl https://raw.githubusercontent.com/xd009642/tarpaulin/master/travis-install.sh)
      - name: run tarpaulin
        env:
          RUSTC_WRAPPER: sccache
        run: cargo tarpaulin -v --out Xml --exclude-files target* --exclude-files depricated/* --all
      - uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{secrets.CODECOV_TOKEN}} #required
          file: ./cobertura.xml
